steps:
  # Create docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/quarkus-vertx', '.']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta run deploy',
      '--image gcr.io/$PROJECT_ID/quarkus-vertx'
      '--region us-central1'
      '--allow-unauthenticated',
      'quarkus-vertx'
    ]

# Image name
images: ['gcr.io/$PROJECT_ID/quarkus-vertx']
